name: deliverzler
description: Delivery App for Restaurants built on Flutter using Domain-Driven Design (DDD) and Riverpod Framework.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # ✅ متوافق مع Flutter SDK
  logging: ^1.2.0

  # StateManagement & DI
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # FP
  fpdart: ^1.1.0
  rxdart: ^0.27.7

  # Connectivity
  connectivity_plus: ^6.0.3

  # Routing
  go_router: ^13.2.0

  # Location
  location: ^7.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  google_maps: ^6.3.0
  flutter_polyline_points: ^3.1.0

  # Apis
  dio: ^5.4.0

  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1

  # LocalStorage
  shared_preferences: ^2.2.2

  flutter_cache_manager: ^3.3.1
  image_picker: ^1.0.7
  image_picker_platform_interface: ^2.9.2

  # Images
  cached_network_image: ^3.3.1
  lottie: ^2.7.0 # ✅ تم التخفيض لحل تعارض http

  # Utils
  mocktail: ^1.0.3
  device_info_plus: ^9.1.2
  fast_immutable_collections: ^10.1.0
  flutter_fadein: ^2.0.0
  uuid: ^4.3.3
  url_launcher: ^6.2.4
  flutter_local_notifications: ^16.3.2
  timeago: ^3.6.1

  # Widgets
  flutter_platform_widgets: ^7.0.0
  flutter_adaptive_scaffold: ^0.3.2
  fluttertoast: ^8.2.4
  qr_flutter: ^4.1.0
  material_floating_search_bar:
    git:
      url: https://github.com/Railway-Engineering-Solutions/material_floating_search_bar.git
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  import_sorter: ^4.6.0

  # Lints
  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10

  # Code gen
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  go_router_builder: ^2.7.1

import_sorter:
  comments: false

flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/map_styles/
    - assets/icons/
    - assets/icons/dialog_widget_icons/
    - assets/icons/languages_icons/
    - assets/icons/screens_icons/
    - assets/images/core/
    - assets/images/login/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700